experiment_name: "Webservice"

mini_batch:
  size: 1
  # N means the number of cluster text in one inference
  # strongly recommend to set N to half ~ two-thirds of your VRAM(GB)

segment:
  args:
    n_word: 30
    n_overlap: 0
    fix_size: False

concat:
  method: "concate_kmeans"
  args:
    k: 5

summary:
  args:
    min_length: 30
    max_length: 1024

save_summaries: False
